# Generated by Django 2.1.7 on 2019-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
